# Generated by Django 4.0.6 on 2022-08-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
